### ISSUE TITLE
Can i do 2 or more mappers for one buisness class with it?

### ISSUE THREAD

**Issue by tremp-m** [squarealfa/dart_framework#12]
hi
i have such question: can i do 2 or more mappers for one buisness class with it? (i want to have some DTOs for one domain object)

**Comment by ruicraveiro** [comment]
Hi,

Out of the box, you have a mapper to JSON and a mapper to the classes generated by protoc compiler (gRPC), so 2 different mappers. Besides the mappers, there is a code generation for a Builder (which basically assumes that your business class is immutable and generates a mutable builder class). There is no support for several mappers of the same kind, though.

Do you have a more concrete example of the use-case you are trying to implement?

**Comment by tremp-m** [comment]
thx for replay. Yes - for example i have some dto class:
```
Class SomeDto{
bool someProperty = false;
}
```

And now i want convert it to json and to sqlite. In Sqllite there is no type bool and i must convert bool to int. In json there is no such problem. Yes - i can in json make this property int too. But json i use for data exchange with other program and for that side would be not clear why bool stored in int....

**Comment by ruicraveiro** [comment]
You could use the https://pub.dev/packages/json_serializable package for the json specific serialization and this framework for sqlite, with the map_mapper, but there is no support for that kind of field specific customisation, except for the primary key. Do you want to explore the framework a little better and propose an improvement, and eventually after that contribute a PR? Also, have in mind that I was very focused on NoSQL while developing the framework, so I am not sure if the framework could be used with SQLite without some improvements. At the very least it is not an ORM.

**Comment by tremp-m** [comment]
Yes i know about json_serializable and use it. But there i didn't find way for 2 variant of serialization. Because of that i make mapper by hand. Ok i will try use json_serializable with this jointly. About PR - may be it's good idea - i'll think about it. Thx.
