### ISSUE TITLE
The example link is broken

### ISSUE THREAD

**Issue by BenVercammen** [squarealfa/dart_framework#13]
The link in the README file for proto_mapper/proto_generator pointing to the example (https://github.com/squarealfa/dart_framework/tree/main/proto_mapper/proto_mapper_example) returns a 404 not found. I suppose this should link to https://github.com/squarealfa/dart_framework/tree/main/proto_mapper/example now?

**Comment by ruicraveiro** [comment]
Thanks for heads up!! The links have been fixed.
