### ISSUE TITLE
Support for polymorphism

### ISSUE THREAD

**Issue by ruicraveiro** [squarealfa/dart_framework#24]
@BenVercammen, while I closed the PR #22, I didn't dismiss the need to use polymorphism in our package.

I had a ton of issues with that PR, not only conceptually, but practical as well. So, in practice adding well-known types is something I'd like to avoid (or dependencies on types brought from any other external library for that matter - I honestly tried to use it, but it is a deal breaker).

However, I considered whether gRPC would support unions as a means to get there and in fact we have this lovely feature called Oneof (which I immediately discovered just now by searching for "grpc unions"): https://developers.google.com/protocol-buffers/docs/proto#oneof

So, lets say we have the following set of classes:

```dart

// New ProtoBase class that represents
// a proto class that has subclasses
class ProtoBase {
  // I think we would need a list of subclasses
  // which isn't ideal
  const ProtoBase(List<Type> subClasses);
}

// this is our super class
@ProtoBase([Car, Airplane])
abstract class Vehicle {
  final int weight;
  Vehicle({
    required this.weight,
  });
}

@proto
class Car extends Vehicle {
  Car({
    required this.numberOfDoors,
    required int weight,
  }) : super(weight: weight);

  final int numberOfDoors;
}

@proto
class Airplane extends Vehicle {
  Airplane({
    required int weight,
    required this.wingspan,
  }) : super(weight: weight);

  final int wingspan;
}

```

We could change the generator, so that it would generate the following protos:

```proto
syntax = "proto3";
      
message GCar
{
  int32 weight = 1;
  int32 number_of_doors = 2;
}   

message GListOfCar
{
  repeated GCar items = 1;
}

message GAirplane
{
  int32 weight = 1;
  int32 wingspan = 2;
}   

message GListOfAirplane
{
  repeated GAirplane items = 1;
}

// This is where the magic would begin.
// Because Vehicle is annotated with ProtoBase instead of Proto,
// the message containing its fields would be GVehicleFields and not GVehicle
message GVehicleFields
{
  int32 weight = 1;
}   

// the message GVehicle would be a union of
// the GVehicleFields, GCar or GAirplane
message GVehicle {
  oneof props {
    GVehicleFields vehicle = 1;
    GCar car = 2;
    GAirplane airplane = 3;
  }
}

message GListOfVehicle
{
  repeated GVehicle items = 1;
}

```

Assuming those protos were left in /lib, after running ```protoc --dart_out=grpc:lib/grpc lib/*.proto -Ilib``` we would get a set of classes that would enable use the generated code as such:

```dart 

  final car = GCar()
    ..numberOfDoors = 4
    ..weight = 1000;

  final airPlane = GAirplane()
    ..weight = 690
    ..wingspan = 15;

  // we would need to change proto_map_generator to also generate this kind of mapping:
  final vehicleList = GListOfVehicle()
    ..items.addAll([
      GVehicle()..airplane = airPlane,
      GVehicle()..car = car,
    ]);

  // this is not intended for persistency, but
  // whatever works for your use-case...
  final json = vehicleList.toProto3Json();
  print(json);

  final receivedList = GListOfVehicle()..mergeFromProto3Json(json);


  for (final vl in receivedList.items) {
    // we would also need to think about proto_map_generator
    // to generate the next set of ifs
    if (vl.hasAirplane()) printAirplane(vl.airplane);
    if (vl.hasCar()) printCar(vl.car);
  }

```

I think this approach would work, and it has a few benefits:
- It supports polymorphism
- It is self-contained without dependencies to external types
- It supports your need to export it to json and back.

Just before pressing "submit", I queried "grpc polymorphism" and found an interesting discussion that covers precisely the two approaches we have seen, any and OneOf: https://groups.google.com/g/protobuf/c/f24-oElV3nM?pli=1

Let me know your thoughts on this approach.

**Comment by BenVercammen** [comment]
Sorry for the late reaction, I have been focussing on some other stuff lately. Looks quite good/useful. 
Only the explicit mapping of ``knownSubclasses`` is a bit unfortunate, it would have been nice if the code generator could somehow figure this out by itself, but that would probably be a bit hard to pull off.
