### ISSUE TITLE
How to add the sdk

### ISSUE THREAD

**Issue by hmbenhaim** [squarealfa/dart_framework#26]
Hi, thank you for your package, I just wander how to add the go sdk to the application is not clear to me, if you can add full example application and not only a dart file it would be amazing thank you.

**Comment by ruicraveiro** [comment]
Hi! I would definitely like to have much better documentation, but I've been prioritizing adding features and stabilizing the package. Would you by chance be willing to help with the documentation? In exchange, I would be happy to do a live presentation with you. If you are interested, give me calendar options and I'll schedule a Google Meeting which I will post here. Have in mind that I am on UTC time zone.

In the meanwhile, if you find it enough, there is complete-ish example under: https://github.com/squarealfa/dart_framework/tree/main/example_model
